### PR TITLE
Upgrade `base64` to `0.21`

### PR DESCRIPTION
**Pull request by MarijnS95**
A new trait-based system has been employed, with implementations for all the configurations rather than those configurations being passed as argument to the free `encode_config()` function.

### CODE REVIEW

**Comment by ramosbugs** [comment]
This crate's MSRV goes back even further than `openidconnect` to Rust 1.45, which I guess is incompatible with this version of `base64`'s use of the 2021 edition.

Whenever version 5.0 of this crate happens (no immediate plans), I'll introduce the same 6-month relaxed MSRV policy that I did in the latest major release of `openidconnect`. But, that change in policy feels like a breaking change, so I'd prefer to wait unless there's a compelling reason (e.g., serious bug fix or security issue).

**Comment by MarijnS95** [comment]
@ramosbugs thanks! No immediate bugs/security issues AFAIK (or RUSTSEC will ring some bells), just pruning duplicates in my dependency trees as most of the ecosystem seems to have adopted `base64 0.21` now.

**Comment by CosminPerRam** [comment]
Hey, just checking in the progress around this crate, would the [db0ea44](https://github.com/ramosbugs/oauth2-rs/commit/db0ea44657bd6c1130b83ce135ac2691ba091fad) commit replace this PR as it's already upgraded in main now?

**Comment by ramosbugs** [comment]
> Hey, just checking in the progress around this crate, would the [db0ea44](https://github.com/ramosbugs/oauth2-rs/commit/db0ea44657bd6c1130b83ce135ac2691ba091fad) commit replace this PR as it's already upgraded in main now?

Yes, both `base64` 0.21 and 0.22 are supported now as of #261. Thanks @MarijnS95 for the PR. I forgot about it and did the upgrade separately when I was doing the breaking `reqwest` version bump 😅

**Pull request closed without merging**
