### PR TITLE
Update dependencies (base64, rand, hmac)

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
Ah, seems like we need to adjust some things for the WASM targets

**Comment by ramosbugs** [comment]
Thanks for the PR! https://rust-random.github.io/book/update-0.8.html#dependencies looks like it has some info about WASM targets and `getrandom`.

**Comment by Cogitri** [comment]
Thanks for the link, should build now :)

**Comment by ramosbugs** [comment]
Thank you!

**Pull request merged**
