### PR TITLE
feat: add const context to wrapper types

### PR DESCRIPTION
**Pull request by MrNossiom**

### CODE REVIEW

**Comment by ramosbugs** [comment]
Seems like a worthwhile improvement, thanks!

**Comment by MrNossiom** [comment]
Thanks. I don't know if I should also add it to the secret wrapper types, since there is a small chance anyone would hardcode their tokens. Not doing so may prevent bad practice.

**Comment by ramosbugs** [comment]
Agreed, let's just do the non-secret types.

**Comment by MrNossiom** [comment]
I think this is the only place adding `const` is useful.
Thanks

**Pull request merged**
